# Generated by Django 6.0.1 on 2026-01-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CONVERSATION', 'Conversation'), ('CALL', 'Call')], max_length=20)),
                ('count_or_duration', models.IntegerField()),
                ('crumbs', models.IntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
