# Generated by Django 6.0.1 on 2026-01-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migajas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('CONVERSATION', 'Conversation'), ('CALL', 'Call'), ('REMOVAL', 'Removal')], max_length=20),
        ),
    ]
